TEST_VALUE:
  name: 'dev_cookie'
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: balabalabala
  FEISHU_APP_SECRET: balabalabala
APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
MYSQL_CONFIG:
  name: "nestweb"
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "root"
  database: "nestweb"
  entities: "mysql" # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true